#your database of choice
#the options are
#MapDBFile
#SQL
database: 'MapDBFile'
# the prefix you'd like your currency to have

#The long version of the prefix
Lprefix: 'CatCoins'
#The short version of the prefix
Sprefix: 'CC'

# if you want to change how often the plugin maintains its internal database sync then uncomment this
# maintain_delay: 144000

# if you want to disable transaction logging set this to false
# do_logs: true