name: Catconomy
version: '${version}'
main: ninekothecat.catconomy.Catconomy
load: STARTUP
softdepend: [ Vault ]
authors: [ nikothenya ]
description: an economy plugin that does not care about the database you use
commands:
  balance:
    description: "get your or another player's balance"
  deposit:
    description: "transfer money to another player"
    aliases: [ 'pay' ]
  catconomy:
    description: "catconomy commands"
    aliases: [ 'cc' ]